#!/run/current-system/sw/bin/bash

window=$(hyprctl activewindow | grep class | awk '{print $2}')
title=$(hyprctl activewindow | grep title | awk '{print $2}')

if [[ $window == "" || $title == "" ]]; then
  echo "..."
  exit 0
fi

toShow="$window - $title"
maxLen=30

suffix=""

# if test $(echo $toShow | wc -c) -ge $maxLen ; then
#   suffix=" ..."
# fi
#

echo "$toShow"

#echo "${toShow:0:$maxLen}$suffix"
