{
  imports = [
    ./com/apparmor.nix
    ./com/bash.nix
    ./com/bcachefs.nix
    ./com/blacklistNvidiaGPU.nix
    ./com/bluetooth.nix
    ./com/bootEFI.nix
    ./com/bootGRUB.nix
    ./com/bootLimine.nix
    ./com/cpu.nix
    ./com/dns.nix
    ./com/doas.nix
    ./com/environment.nix
    ./com/fhb.nix
    ./com/fonts.nix
    ./com/fstrim.nix
    ./com/gnupg.nix
    ./com/governor.nix
    ./com/intelGPU.nix
    ./com/kbd.nix
    ./com/kernel.nix
    ./com/locale.nix
    ./com/minio-client.nix
    ./com/network.nix
    ./com/nh.nix
    ./com/nix.nix
    ./com/nix-ld.nix
    ./com/nixpkgs.nix
    ./com/nvidiaGPU.nix
    ./com/openssh.nix
    ./com/pam.nix
    ./com/pipewire.nix
    ./com/podman.nix
    ./com/qemuguest.nix
    ./com/security.nix
    ./com/settings.nix
    ./com/sops.nix
    ./com/state.nix
    ./com/sudo-rs.nix
    ./com/thermald.nix
    ./com/timezone.nix
    ./com/tpm2.nix
    ./com/udisks.nix
    ./com/users.nix
    ./com/virt-manager.nix
    ./com/vmVariant.nix
    ./com/waydroid.nix
    ./com/yubikey.nix
    ./com/zfs.nix
    ./com/zram.nix
    ./com/zsh.nix

    ./gui/hyprland
    ./gui/mango
    ./gui/niri

    ./oci/changedetection
    ./oci/filebrowser
    ./oci/firefly
    ./oci/forgejo
    ./oci/immich
    ./oci/jellyfin
    ./oci/jellyseerr
    ./oci/lidarr
    ./oci/linkwarden
    ./oci/newt
    ./oci/paperless
    ./oci/pgadmin
    ./oci/prowlarr
    ./oci/radarr
    ./oci/romm
    ./oci/rustfs
    ./oci/sonarr
    ./oci/syncthing
    ./oci/torrent
    ./oci/transcode
    ./oci/vaultwarden

    ./programs/alvr
    ./programs/appimages
    ./programs/direnv
    ./programs/dolphin
    ./programs/firejail
    ./programs/ghidra
    ./programs/kicad
    ./programs/localsend
    ./programs/nautilus
    ./programs/steam
    ./programs/thunar
    ./programs/weylus

    ./services/arr
    ./services/borg
    ./services/clamav
    ./services/flatpak
    ./services/frigate
    ./services/k3s
    ./services/mullvad
    ./services/n8n
    ./services/nfsv4
    ./services/node-exporter
    ./services/ollama
    ./services/open-webui
    ./services/openrgb
    ./services/promtail
    ./services/qdrant
    ./services/sunshine
    ./services/syncthing
    ./services/vpn

    ./style/default.nix
  ];
}
