{
  imports = [
    ./data/postgres/asgard.nix
    ./data/postgres/base.nix
    ./metal/bash.nix
    ./metal/bootEFI.nix
    ./metal/bootGRUB.nix
    ./metal/cpu.nix
    ./metal/docs.nix
    ./metal/environment.nix
    ./metal/fhb.nix
    ./metal/governor.nix
    ./metal/kernel.nix
    ./metal/locale.nix
    ./metal/network.nix
    ./metal/nix.nix
    ./metal/nixpkgs.nix
    ./metal/promtail.nix
    ./metal/sops.nix
    ./metal/state.nix
    ./metal/timezone.nix
    ./metal/users.nix
    ./metal/vmVariant.nix
    ./metal/zfs.nix
    ./metal/zram.nix
    ./metal/template/abyss.nix
    ./metal/template/yggdrasil.nix
    ./net/node-exporter.nix
    ./net/openssh.nix
    ./net/sunshine.nix
    ./net/service/borg/abyss.nix
    ./net/service/borg/aegir.nix
    ./net/service/borg/asgard.nix
    ./net/service/borg/heimskringla.nix
    ./net/service/borg/yggdrasil.nix
    ./net/service/home/frigate.nix
    ./net/service/home/home-assistant.nix
    ./net/service/media/aegir.nix
    #./net/service/minecraft/tesseract.nix
    ./net/service/monitoring/gotify.nix
    ./net/service/monitoring/grafana.nix
    ./net/service/monitoring/homepage.nix
    ./net/service/monitoring/loki.nix
    ./net/service/monitoring/prometheus.nix
    ./net/service/storage/gitea.nix
    ./net/service/storage/nextcloud.nix
    ./net/service/syncthing/base.nix
    ./net/service/syncthing/abyss.nix
    ./net/service/syncthing/yggdrasil.nix
    ./net/vpn/openvpn
    ./programs/appimages.nix
    ./programs/firejail.nix
    ./programs/gnupg.nix
    ./programs/hyprland.nix
    ./programs/localsend.nix
    ./programs/steam.nix
    ./programs/weylus.nix
    ./programs/zsh.nix
    ./services/flatpak.nix
    ./services/sddm.nix
    ./system/fstrim.nix
    ./system/logrotate.nix
    ./system/openrgb.nix
    ./system/pipewire.nix
    ./system/qemuguest.nix
    ./system/udisks.nix
    ./system/xserver.nix
    ./virtualisation/virt-manager.nix
    ./virtualisation/podman.nix
    ./virtualisation/waydroid.nix
    ./virtualisation/oci/immich.nix
    ./virtualisation/oci/paperless.nix
    ./virtualisation/oci/torrent.nix
    ./virtualisation/oci/transcode.nix
  ];
}
