theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
clipboard-provider = "wayland"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
